<?php

use Drupal\Core\Url;
use Drupal\Core\Entity\EntityInterface;

/**
  * Implements hook_theme().
*/

function view_mode_path_theme($existing, $type, $theme, $path) {
  return [
    'view_mode_path_image_modal_link' => [
      'variables' => [
        'item' => NULL,
        'item_attributes' => NULL,
        'url' => NULL,
        'image_style' => NULL,
        'attributes' => NULL
      ],
    ]
  ];
}

/**
 * NOTE: This is whole-sale copy/paste from template_preprocess_image_formatter.
 * I couldn't figure out how to import that function from image.field.inc.
 *
 * @param array $variables
 *   An associative array containing:
 *   - item: An ImageItem object.
 *   - item_attributes: An optional associative array of html attributes to be
 *     placed in the img tag.
 *   - image_style: An optional image style.
 *   - url: \Drupal\Core\Url object.
 *   - attributes: go on anchor tag
 */
function template_preprocess_view_mode_path_image_modal_link(&$variables) {
  if ($variables['image_style']) {
    $variables['image'] = [
      '#theme' => 'image_style',
      '#style_name' => $variables['image_style'],
    ];
  }
  else {
    $variables['image'] = [
      '#theme' => 'image',
    ];
  }
  $variables['image']['#attributes'] = $variables['item_attributes'];

  $item = $variables['item'];

  // Do not output an empty 'title' attribute.
  if (mb_strlen($item->title) != 0) {
    $variables['image']['#title'] = $item->title;
  }

  if (($entity = $item->entity) && empty($item->uri)) {
    $variables['image']['#uri'] = $entity->getFileUri();
  }
  else {
    $variables['image']['#uri'] = $item->uri;
  }

  foreach (['width', 'height', 'alt'] as $key) {
    $variables['image']["#$key"] = $item->$key;
  }
}

function view_mode_path_get_url(EntityInterface $entity, $view_mode = 'default'){
  if ($entity->getEntityTypeId() == 'node') {
    $route = 'view_mode_path.node';
  }
  else if($entity->getEntityTypeId() == 'media') {
    $route = 'view_mode_path.media';
  }
  else {
    return NULL;
  }
  $url = Url::fromRoute($route, ['id' => $entity->id(), 'view_mode' => $view_mode]);
  return $url;
}
